version: '3.8'

services:
  postgres:
    container_name: postgres-prisma
    image: postgres:latest
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: cscaleTestPassword
      POSTGRES_DB: mydb
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
